# ===================== Spring =====================
server.port: 8080

# =================== Datasource ===================
spring:
  jpa:
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping_list
    username: user
    password: password
  sql.init.platform: postgres